### ISSUE TITLE
Works on MacOsx?

### ISSUE THREAD

**Issue by douglasjunior** [ncornette/gimp-android-xdpi#5]
I'm trying to use the plugin on MacOsx Yosemite. I'm using Gimp 2.8.

I'm trying to copy on: Macintosh HD ▸ Users ▸ douglas ▸ Library ▸ Application Support ▸ GIMP ▸ 2.8 ▸ plug-ins

And: Macintosh HD ▸ Applications ▸ GIMP.app ▸ Contents ▸ Resources ▸ lib ▸ gimp ▸ 2.0 ▸ plug-ins

But not appear Android option in the Filters menu.

**Comment by dandalf** [comment]
Check this out: http://www.gimptalk.com/index.php?/topic/36105-adding-scripts-to-gimp-using-a-mac-easy-10-step-tutorial/

I put my plugins in ~/Application Support/GIMP/2.8/scripts/ and added that to my gimp folders preference.

**Comment by douglasjunior** [comment]
Same problem. :cry: 

I configured the folder:
![captura de tela 2015-07-27 as 15 52 35](https://cloud.githubusercontent.com/assets/1512341/8914799/af73b008-3477-11e5-860a-3bc3a6dfa1db.png)

Copied the file:
![captura de tela 2015-07-27 as 15 52 48](https://cloud.githubusercontent.com/assets/1512341/8914809/bc4d153a-3477-11e5-9dc5-44c881932b3e.png)

Restart the Gimp, and Android filter not appears:
![captura de tela 2015-07-27 as 15 53 08](https://cloud.githubusercontent.com/assets/1512341/8914829/ce481460-3477-11e5-9fc9-50da58065cf9.png)

**Comment by dandalf** [comment]
Sorry, I wrote scripts and I meant plugins.  You actually need to modify the plugins folder:
I put my plugins in ~/Application Support/GIMP/2.8/plug-ins/ and added that to my gimp folders preference as one of the plug-ins folders.

**Comment by douglasjunior** [comment]
In my original question I also tried the Plugins folder. It does not work either.

**Comment by dandalf** [comment]
Try removing the GIMP Scripts folder from the scripts list and add it to plugins folder list.

Sorry that it's not working, I have it working on my mac using the plug-ins folder.  As an alternative, if you goto Help -> Plug-In Browser and search for "android", the second option appears to be this script.

**Comment by douglasjunior** [comment]
I tried remove folder from Scripts, tried create others folders, tried everything. :cry: 
Not appears in the Plugin Browsers.
Thanks for the tips.

**Comment by jasemagee** [comment]
On Linux I needed to set the script file to be executable. Might be the same on Mac?

**Comment by douglasjunior** [comment]
YES! 
```
chmod +x gimpfu_android_xdpi.py 
```
Now it works! Thanks! Thank you all!
